# My own bin directory
export PATH=$PATH:$HOME/.bin

# NVM
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

# RVM
PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

# Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

# Cargo
export PATH="$HOME/.cargo/bin:$PATH"
