# My own bin directory
export PATH=$PATH:$HOME/.bin

# RVM
PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

# Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

# Cargo
export PATH="$HOME/.cargo/bin:$PATH"

# Java
export JAVA_HOME=/Library/Java/JavaVirtualMachines/amazon-corretto-8.jdk/Contents/Home
export JAVA_HOME=/Library/Java/JavaVirtualMachines/amazon-corretto-8.jdk/Contents/Home
